#!/usr/bin/env php
<?php
declare(strict_types=1);

use Laminas\Cli\ApplicationFactory;
use Laminas\Cli\ContainerResolver;#!/usr/bin/env php


// Composer autoloading
include __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';


$applicationFactory = new ApplicationFactory();
exit($applicationFactory(ContainerResolver::resolve())->run());