
[program:php7.4-fpm]
command=/bin/sh -c "mkdir -p /run/php/ && /usr/sbin/php-fpm7.4 -R -F -c /etc/php/7.4/fpm/php-fpm.conf"
process_name=%(program_name)s_%(process_num)02d
numprocs=1
redirect_stderr=true
autostart=true
autorestart=true
user=root
# To make supervisor to kill the child processes too @START
killasgroup=true
stopasgroup=true
# To make supervisor to kill the child processes too @END

startsecs=0
startretries=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
