<?php
/** @var Laminas\View\Renderer\PhpRenderer $this */
$this->render('blog/assets');
$entry = $this->entry;
$title = $entry->getTitle();
$this->headTitle()->prepend($title);
$title = $this->escapeHtml($title);
$url   = $this->url('phly-blog/entry', array('id' => $entry->getId()));
$ds    = function ($ts) use ($entry) {
	$tz   = $entry->getTimezone();
	$date = new \DateTime();
	$date->setTimezone(new \DateTimeZone($tz));
	$date->setTimestamp($ts);
	return $date->format('Y-m-d H:i:s');
};
// @codingStandardsIgnoreEnd
foreach ($this->headTitle() as $blogTitle) {}
// @codingStandardsIgnoreEnd
$this->headLink(array(
	'href'  => $this->url('blog/feed-atom'),
	'type'  => 'application/atom+xml',
	'rel'   => 'alternate',
	'title' => $blogTitle . ' Atom Feed',
));
$this->headLink(array(
	'href'  => $this->url('blog/feed-rss'),
	'type'  => 'application/rss+xml',
	'rel'   => 'alternate',
	'title' => $blogTitle . ' RSS Feed',
));
?>

<div class="container">
  <div class="row mt-5">
	<div class="col-md-12">
	  <h2><?php echo ucfirst($title) ?></h2
	  <hr>
	<div>
	  <p>Written on <?php echo $ds($entry->getCreated()) ?> </p>
	  <p>Last updated <?php echo $ds($entry->getUpdated()) ?></p>
	  <ul>
		  <?php foreach ($entry->getTags() as $k => $tag) : ?>
			<li><a href="<?php echo $this->url('blog/tag', ['name' => $tag]) ?>"
				   class="ml-1"><?php echo ucfirst($tag) ?> </a></li>
		  <?php endforeach; ?>
	  </ul>
	</div>

	  <article>
		<?php echo $entry->getBody(); echo $entry->getExtended(); ?>
		<div class="mt-5">
		  <a href="<?=$this->url('blog/index') ?>">Return to entries</a>
		</div>
	  </article>
	  <div class="mt-5">
		  <?php echo $this->disqus($entry->getId(), $url, $title) ?>
	  </div>
	</div>
  </div>
</div>