<div>
  <h2 class="blog-post-title"><a href="/blog/2019-09-10-git-useful-commands.html">Git useful commands</a></h2>
    <ul>
<li>Store all your cred into system helper</li>
</ul>
<pre><code class="language-bash">git config --global credential.helper store
# Set the cache to timeout after 1 hour (setting is in seconds)
git config --global credential.helper 'cache --timeout=3600'
</code></pre>  <footer>
    <p class="text-right">
      <a href="/blog/2019-09-10-git-useful-commands.html">Continue reading...</a>
    </p>
  </footer>
</div><div>
  <h2 class="blog-post-title"><a href="/blog/2020-12-17-nmap-useful-commands.html">Nmap useful commands</a></h2>
    <p>Look up which ip is used by which host</p>
<pre><code class="language-bash">nmap -sn 192.168.1.0/24
</code></pre>  <footer>
    <p class="text-right">
      <a href="/blog/2020-12-17-nmap-useful-commands.html">Continue reading...</a>
    </p>
  </footer>
</div>