<?php
//$this->layout()->single = true;
$this->render('blog/assets');

$paginatorUrl = $this->paginator_url;
$urlSubstitutionString = $this->substitution;
$basePageUrl = str_replace('-p%d', '', $paginatorUrl);
if ($urlSubstitutionString) {
    $basePageUrl = str_replace('%s', str_replace(' ', '+', $urlSubstitutionString), $basePageUrl);
}

// Set head title
$this->headTitle()->prepend($this->title);

// Add feed links
$this->headLink(array(
    'href' => $this->url('blog/feed-atom'),
    'type' => 'application/atom+xml',
    'rel' => 'alternate',
    'title' => $this->title . ' Atom Feed',
));
$this->headLink(array(
    'href' => $this->url('blog/feed-rss'),
    'type' => 'application/rss+xml',
    'rel' => 'alternate',
    'title' => $this->title . ' RSS Feed',
));
$ds    = function ($entry)  {
    $tz   = $entry->getTimezone();
    $date = new \DateTime();
    $date->setTimezone(new \DateTimeZone($tz));
    $date->setTimestamp($entry->getCreated());
    return $date->format('Y-m-d H:i:s');
};
?>
<div class="container">
    <?php foreach ($this->entries as $entry): ?>
      <article class="blog-post">
          <?php echo $this->render('blog/entry-short', array('entry' => $entry)); ?>
      </article><!-- /.blog-post -->
      <hr>
    <?php endforeach;?>
    <?=$this->paginationControl($this->entries, 'Sliding', 'blog/paginator', array('url' => $paginatorUrl, 'substitution' => $urlSubstitutionString,)) ?>
</div>