<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">

    <?= $this->headTitle('VRKANSAGARA')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/images/favicon.ico'])
        ->prependStylesheet($this->basePath('assets/css/app.css'))
        ->prependStylesheet($this->basePath('assets/css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>

    <link rel="canonical" href="<?=$this->url()?>">
</head>
<body class="d-flex flex-column h-100">

<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?=$this->url('home')?>">Vallabh Kansagara (VRKANSAGARA)</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto mb-2 mb-md-0">
                    <li class="nav-item active">
                        <a class="nav-link" aria-current="page" href="<?=$this->url('home')?>">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="<?=$this->url('projects')?>"id="projects" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Projects</a>
                        <div class="dropdown-menu" aria-labelledby="projects">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" aria-current="page" href="<?=$this->url('home')?>">Blog</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" aria-current="page" href="<?=$this->url('resume')?>">Resume</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" aria-current="page" href="<?=$this->url('contact')?>">Contact</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" aria-current="page" href="<?=$this->url('about')?>">About</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control mr-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</header>

<?= $this->content ?>

<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">
            <div class="row">
                <div class="col-md-2">
                    <span><a target="_blank" href="https://imjo.in/3aZSG9">Buy me a coffee.</a></span>
                </div>
                <div class="col-md-8">
                    <p>Unless otherwise noted © 2015 - <?= date('Y') ?>, Vallabh Kansagara ( 56 52 4B 41 4E 53 41 47 41 52 41  )</p>
                </div>
                <div class="col-md-2 pull-right">Execution time:</div>
            </div>


    </div>
</footer>

<?= $this->inlineScript()
//    ->prependFile($this->basePath('assets/js/bootstrap.min.js'))
    ->prependFile($this->basePath('assets/js/bootstrap.bundle.min.js'))
?>
</body>
</html>
