<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Title -->
    <?= $this->headTitle('VRKANSAGARA')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0 shrink-to-fit=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendHttpEquiv('description', 'Vallabh Kansagara (VRKANSAGARA)')
        ->appendHttpEquiv('author', 'Vallabh Kansagara (VRKANSAGARA)')
    ?>

    <!-- Favicon -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath('/assets/favicon/favicon.ico'
        )])
        ->prependStylesheet('https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css')
        ->prependStylesheet($this->basePath('/assets/css/theme.bundle.css'))
        ->prependStylesheet($this->basePath('/assets/css/libs.bundle.css'))

    ?>

  <!-- Scripts -->
    <?= $this->headScript() ?>
  <link rel="canonical" href="<?= $this->url('home') ?>">

    <?php if (is_production_mode()): ?>
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script data-cfasync="false" async src="https://www.googletagmanager.com/gtag/js?id=UA-62451902-2"></script>
      <script>
          window.dataLayer = window.dataLayer || [];

          function gtag() {
              dataLayer.push(arguments);
          }

          gtag('js', new Date());

          gtag('config', 'UA-62451902-2');
      </script>
    <?php endif; ?>

</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">
        <span class="d-block d-lg-none">Vallabh Kansagara</span>
        <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="<?=$this->basePath('assets/images/vrkansagara.jpeg')?>" alt="" /></span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="<?= $this->url('home') ?>">Home</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="<?=$this->url('blog')?>">Blog</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#experience">Experience</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#education">Education</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#skills">Skills</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#interests">Interests</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#awards">Awards</a></li>
            <li>
                <form method="get" action="s" class="d-flex"> <input name="name" value="" id="searchAnyThing" class="form-control mr-2" type="search" placeholder="Search anything..." aria-label="Search anything..."> </form>
            </li>
        </ul>
    </div>
</nav>

<!-- Begin page content -->
<?= $this->content ?>

<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
                    <span>
                      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cup-fill" fill="currentColor"
                           xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd"
        d="M1 2a1 1 0 0 1 1-1h11a1 1 0 0 1 1 1v1h.5A1.5 1.5 0 0 1 16 4.5v7a1.5 1.5 0 0 1-1.5 1.5h-.55a2.5 2.5 0 0 1-2.45 2h-8A2.5 2.5 0 0 1 1 12.5V2zm13 10h.5a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.5-.5H14v8z"/>
</svg>
                      <a target="_blank" href="https://imjo.in/3aZSG9">Buy me a coffee.</a>
                    </span>
      </div>
      <div class="col-md-8">
        <p>Unless otherwise noted © 2015 - <?= date('Y') ?>, Vallabh Kansagara ( 56 52 4B 41 4E 53 41 47 41 52 41 )</p>
      </div>
      <div class="col-md-2 pull-right">Execution time:</div>
    </div>
  </div>
</footer>


<!-- Font Awesome icons (free version)-->
<script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>-->
<!-- Third party plugin JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

<!-- Map JS -->
<script src='https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>


<?php
echo $this->inlineScript()
    ->prependFile($this->basePath('/assets/js/theme.bundle.js'), 'text/javascript', ['defer' => false])
    ->prependFile($this->basePath('/assets/js/vendor.bundle.js'), 'text/javascript', ['defer' => false])
?>
</body>
</html>
