<!-- Contact Us Section -->
<div class="container">
    <div class="row">
        <!-- Section Title -->
        <div class="col-md-12">
            <h2>Love to Hear From You</h2>
        </div>
    </div>
    <div class="row pb-4">
        <!-- Section Title -->
        <div class="col-md-6 mt-3">

            <table>
                <tr>
                    <td>Address</td>
                    <td>Ahmedabad, Gujarat, India</td>
                </tr>
                <tr>
                    <td>Phone</td>
                    <td>(+91) 9xxxx-xxx59</td>
                </tr>

                <tr>
                    <td>Website</td>
                    <td><a target="_blank" href="https://vrkansagara.in">https://vrkansagara.in</a></td>
                </tr>
                <tr>
                    <td>Twitter</td>
                    <td><a target="_blank" href="https://twitter.com/vrkansagara">vrkansagara</a></td>
                </tr>
                <tr>
                    <td>Facebook</td>
                    <td><a target="_blank" href="https://facebook.com/vrkansagara">vrkansagara</a></td>
                </tr>
                <tr>
                    <td>Github</td>
                    <td><a target="_blank" href="https://github.com/vrkansagara">vrkansagara</a></td>
                </tr>
                <tr>
                    <td>LinkedIn</td>
                    <td><a target="_blank" href="https://www.linkedin.com/in/vrkansagara">vrkansagara</a></td>
                </tr>
                <tr>
                    <td>Instagram</td>
                    <td><a target="_blank" href="https://www.instagram.com/vrkansagara/">vrkansagara</a></td>
                </tr>
            </table>

        </div>
        <div class="col-md-6 mt-3">
            <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d470029.1604841957!2d72.29955005258641!3d23.019996818380896!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x395e848aba5bd449%3A0x4fcedd11614f6516!2sAhmedabad%2C%20Gujarat!5e0!3m2!1sen!2sin!4v1605018211963!5m2!1sen!2sin"
                    width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false"
                    tabindex="0"></iframe>
        </div>
        <!-- contact form -->
        <!-- <div class="col-md-6">
            <form class="shake" role="form" method="post" id="contactForm" name="contact-form" >
                Name
                <div class="form-group ">
                  <label class="control-label" for="name">Name</label>
                  <input class="form-control" id="name" type="text" name="name" required data-error="Please enter your name">

                </div>
                email
                <div class="form-group ">
                  <label class="control-label" for="email">Email</label>
                  <input class="form-control" id="email" type="email" name="email" required data-error="Please enter your Email">

                </div>
                Subject
                <div class="form-group ">
                  <label class="control-label">Subject</label>
                  <input class="form-control" id="msg_subject" type="text" name="subject" required data-error="Please enter your message subject">

                </div>
                Message
                <div class="form-group ">
                    <label for="message" class="control-label">Message</label>
                    <textarea class="form-control" rows="3" id="message" name="message" required data-error="Write your message"></textarea>

                </div>
                Form Submit
                <div class="form-submit mt-5">
                    <button class="btn btn-common" type="submit" id="form-submit"><i class="material-icons mdi mdi-message-outline"></i> Send Message</button>
                </div>
            </form>
        </div> -->

    </div>
</div>