<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="container-fluid p-0">
    <!-- Home-->
    <section class="resume-section" id="home">
        <div class="resume-section-content">
            <h2 class="mb-0">
                Vallabh
                <span class="text-primary">Kansagara</span>
            </h2>
            <h3 class="mb-0">
                Development Technical Leader at
                <span class="text-primary">Commerce Pundit</span>
            </h3>
            <div class="subheading mb-5">
                Ahmedabad, Gujarat, India ·
                <a href="mailto:vrkansagara@gmail.com">vrkansagara@gmail.com</a>
            </div>
            <p class="lead mb-5">
                I'm Vallabh Kansagara. I am a software engineer and PHP expert. I write the tools that PHP developers use to build their applications. I am experienced in leveraging agile frameworks to provide a robust synopsis for high level overviews using
                <a href="https://laravel.com/">Laravel</a>
                <a href="https://framework.zend.com/">Zend Framework</a>
                <a href="https://getlaminas.org/">Laminas</a>
                and
                <a href="https://www.php.net/">Core PHP.</a>
            </p>
            <div class="social-icons">
                <a class="social-icon" href="https://www.github.com/vrkansagara"><i class="fab fa-github"></i></a>
                <a class="social-icon" href="https://www.linkedin.com/in/vrkansagara"><i class="fab fa-linkedin-in"></i></a>
                <a class="social-icon" href="https://www.twitter.com/vrkansagara"><i class="fab fa-twitter"></i></a>
                <a class="social-icon" href="https://www.facebook.com/vrkansagara"><i class="fab fa-facebook-f"></i></a>
            </div>
        </div>
    </section>
</div>
