<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<!-- Begin page content -->
<main class="flex-shrink-0">
    <div class="container mt-5">
        <div class="container">

            <div class="row mb-3">
                <div class="col-md-3 themed-grid-col">
                    <img class="bd-placeholder-img card-img-top"
                         width="100%" height="100%"
                         src="<?=$this->basePath('/assets/images/vrkansagara.jpeg')?>" alt="Vallabh Kansagara (VRKANSAGARA)">
                </div>
                <div class="col-md-9 themed-grid-col">
                    <h1 class="display-3">Hello, world!</h1>
                    <p>My name is Vallabh Kansagara (VRKANSAGARA). I am
                    <ul>
                        <li>A day by Software Engineering.</li>
                        <li>A PHP Programmer.</li>
                        <li>A LAMP Stack Web Developer.</li>
                        <li>An Open Source Contributor.</li>
                        <li>A day by the blog writer.</li>
                        <li>Also I do tweet known as <a href="https://twitter.com/vrkansagara">@vrkansagara</a></li>
                        <li>Open source contributor at @GitHub with various projects.</li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </div>
</main>
